[vars]
project = "dailies"

[env]
CHROME_BIN = "/usr/bin/chromium"

[tasks.run]
description = "Run the application"
run = "go run ."

[tasks.clean]
description = "Clean build and test artifacts"
run = ["rm -rf build", "rm -f *.out *.html *.db", "go clean -testcache"]

[tasks.dev]
description = "Standard development workflow"
depends = ["dependencies", "format", "analysis", "test", "ctags"]
alias = "d"

[tasks.ctags]
description = "Generate ctags for the project"
run = ["ctags -R -a --quiet"]

[tasks.dependencies]
description = "Install dependencies"
alias = "deps"
hide = true
run = ["go mod download", "go mod tidy"]

[tasks.format]
description = "Format code"
alias = "fmt"
hide = true
run = ["go fmt ./...", "prettier -lw ."]

[tasks.analysis]
description = "Run a static code analyzer"
alias = "vet"
hide = true
run = "go vet ./..."

[tasks.test]
description = "Run tests"
run = "go test -tags=coverage ./... -cover"

[tasks.build]
run = ["go build -o build/api"]

[tasks.coverage]
description = "Run tests with coverage report"
alias = "cov"
run = [
  "go test ./... -coverprofile=coverage.out",
  "go tool cover -html=coverage.out -o coverage.html",
  "go tool cover -func=coverage.out",
]

[tasks.sloc]
description = "Count lines of code"
run = "tokei -C -e '*_test.go' -e '*-lock.json'"
